export const ADD_NEW_DISH_REQUEST = 'ADD_NEW_DISH_REQUEST';
export const ADD_NEW_DISH_SUCCESS = 'ADD_NEW_DISH_SUCCESS';
export const ADD_NEW_DISH_FAILURE = 'ADD_NEW_DISH_FAILURE';
export const INPUT_CHANGE = 'INPUT_CHANGE';